### PR TITLE
Find JIRA Tickets in Commits

### PR DESCRIPTION
**Pull request by mikian**
Find JIRA Ticket mentions also in commit messages.

(Also little clean and removed executable bits from normal files)

### CODE REVIEW

**Comment by RestlessThinker** [comment]
@mikian Thanks for the PR! What are your thoughts on making the commit messages and optional parameter that defaults to false? The reason I'm suggesting this is that I believe the current version of your PR, would introduce a different experience to what users are expecting.

Also, I've never seen PR changes for removing executable bits from normal files, can you briefly explain what you changed? The PR shows zero changes. Thanks!

**Comment by mikian** [comment]
@RestlessThinker Thanks for feedback, made sense and I agree - so new things are optional now.
About removing executable bits - I literally just ran `chmod a-x ...` command and committed changes. Diff does show file mode changes, that was all.

**Comment by RestlessThinker** [comment]
@mikian - Thanks for updating this. One small change... can you make `report_missing:` default to `true`? It's the previous behavior. Thanks!

**Comment by mikian** [comment]
Done - sorry for that, completely missed switching flag back to original behaviour.

**Review by RestlessThinker — APPROVED** [review]

**Comment by RestlessThinker** [comment]
@mikian Thanks again! I just pushed the latest gem with this change! 💪

**Pull request merged**
